apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backend
  name: backend-monitor
  namespace: monitoring       
  labels:
    release: prometheus       
    app: backend
spec:
  selector:
    matchLabels:
      app: backend          
  namespaceSelector:
    matchNames:
      - default               
  endpoints:
    - port: backend          
      path: /metrics          
      interval: 5s           
